---
- name: Create a VM on ESXi Host
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    esxi_hostname: "192.168.75.128"
    esxi_username: "root"
    esxi_password: "Digvijay@1988"
    datastore_name: "datastore1"
    vm_name: "test-vm"
    vm_guest_id: "centos64Guest"
    vm_cpu: 2
    vm_memory: 2048
    vm_disk_size: 20  # in GB
    vm_network: "VM Network"
    vm_folder: "/vmfs/volumes/{{ datastore1 }}/"
    vm_iso_path: "[{{ datastore_name }}] ISO/CentOS-7-x86_64-Minimal.iso"

  tasks:
    - name: Create a new VM on ESXi
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        datacenter: "ha-datacenter"
        folder: "/"
        name: "{{ vm_name }}"
        state: poweredoff
        guest_id: "{{ vm_guest_id }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
          scsi: paravirtual
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ datastore_name }}"
        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "192.168.1.101"
            netmask: "255.255.255.0"
            gateway: "192.168.1.1"
              #        cdrom:
              #type: iso
              #iso_path: "{{ vm_iso_path }}"
              #wait_for_ip_address: no
              # delegate_to: localhost

    - name: Power on the VM
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        state: powered-on
      delegate_to: localhost

