---
- name: install packages
  hosts: ubuntu
  remote_user: become
  become: yes
  tasks:
    - name: install tree 
      apt:
        name: tree
        state: latest
  
- name: install packages
  hosts: webserver
  remote_user: root
  become: yes
  tasks:
    - name: install tree
      yum:
        name: tree
        state: latest
