- name: Search for a specific file and display its path
  hosts: allservers
  become: false
  gather_facts: false

  vars:
    # --- Configuration Variables ---
    search_path: "/etc"
    file_name: "fstab"
    # -------------------------------

  tasks:
    - name: Find the specified file
      ansible.builtin.find:
        paths: "{{ search_path }}"
        patterns: "{{ file_name }}"
        recurse: yes
      register: file_search_result

    - name: Display the full path if the file is found
      ansible.builtin.debug:
        msg: "File found! Full path: {{ file_search_result.files[0].path }}"
      when: file_search_result.files|length > 0
