
---
- name: reboot rocky linux systems
  hosts: webserver
  become: true
  gather_facts: true
  tasks:
    -  name: Reboot Rocky Linux systems and wait for them to return
       ansible.builtin.reboot:
         pre_reboot_delay: 5
         post_reboot_delay: 10
         reboot_timeout: 60 
       when: ansible_distribution=="Rocky"
    - name: display the uptime
      ansible.builtin.command: uptime
      register: command_output
    - name: print uptime
      ansible.builtin.debug:
        msg: " {{command_output}} "     
