- name: Create AWS EC2 keypair
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create keypair
      amazon.aws.ec2_key:
        name: prod-key
        region: eu-north-1
        state: present
      register: keypair

    - name: Save private key locally
      copy:
        content: "{{ keypair.key.private_key }}"
        dest: "~/.ssh/prod-key.pem"
        mode: '0400'
      when: keypair.changed

