---
- name: Monitoring Server(Prometheus)
  hosts: prometheus
  become: yes

  roles:
    - role: prometheus
      tags: prometheus

    - role: grafana
      tags: grafana

- name: Monitored Hosts
  hosts: monitoredservers
  become: yes

  roles:
    - role: node_exporter
      tags: node_exporter
   
    - role: cadvisor
      tags: cadvisor
