- name: Decommission VM in vSphere
  hosts: localhost
  gather_facts: no

  collections:
    - community.vmware

  vars:
    vcenter: vc.lab.local
    user: administrator@vsphere.local
    pass: VMware@123
    dc: DC1
    vm_name: app01

  tasks:
    - name: Power off VM
      vmware_guest:
        hostname: "{{ vcenter }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        validate_certs: no
        datacenter: "{{ dc }}"
        name: "{{ vm_name }}"
        state: poweredoff

    - name: Delete VM permanently
      vmware_guest:
        hostname: "{{ vcenter }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        validate_certs: no
        datacenter: "{{ dc }}"
        name: "{{ vm_name }}"
        state: absent
        delete_from_inventory: yes

