- name: Failover VM to DR Site
  hosts: localhost
  gather_facts: no

  collections:
    - community.vmware

  vars:
    vcenter: dr-vc.lab.local
    user: administrator@vsphere.local
    pass: VMware@123
    dc: DR-DC
    cluster: DR-CLUSTER
    datastore: dr-datastore
    network: DR_Network
    vm_name: app01-dr
    template: rocky-template-dr
    ip: 172.16.10.50

  tasks:
    - name: Provision DR VM
      vmware_guest:
        hostname: "{{ vcenter }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        validate_certs: no
        datacenter: "{{ dc }}"
        cluster: "{{ cluster }}"
        name: "{{ vm_name }}"
        template: "{{ template }}"
        datastore: "{{ datastore }}"
        state: poweredon

        networks:
          - name: "{{ network }}"
            ip: "{{ ip }}"
            netmask: 255.255.255.0
            gateway: 172.16.10.1

        customization:
          hostname: "{{ vm_name }}"

