- name: Create VM snapshot
  hosts: localhost
  gather_facts: no

  collections:
    - community.vmware

  vars:
    vcenter: vc.lab.local
    user: administrator@vsphere.local
    pass: VMware@123
    dc: DC1
    vm_name: app01

    snapshot_name: before_patch
    snapshot_description: Snapshot before OS patching

  tasks:
    - name: Create snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        validate_certs: no
        datacenter: "{{ dc }}"
        name: "{{ vm_name }}"
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_description }}"
        state: present
        memory_dump: no
        quiesce: yes

